name: Release on PyPI and deploy docs

on:
  push:
    tags:
      - 'v*' 

jobs:
  
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Publish to PyPI
        run: |
          uv build
          uv publish

  
  
  deploy-docs:
    runs-on: ubuntu-latest
      
    needs: publish-to-pypi  # Ensure this job runs only after publish-to-pypi succeeds
      
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force

  
